<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Fonts\**\*" />
    <EmbeddedResource Include="Samples\**\*" />
    <EmbeddedResource Include="Textures\**\*" />
    <EmbeddedResource Include="Tracks\**\*" />
    <EmbeddedResource Include="saber\**\*"/>
    <EmbeddedResource Include="Skins\**\*"/>
  </ItemGroup>
    <ItemGroup>
  <None Update="Songs\**\*">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  </ItemGroup>
  <ItemGroup>
  <None Update="Skins\**\*">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  </ItemGroup>
</Project>
